stages:
  - test

test-plone-5.0-py2:
  tags:
    - nix
  stage: test
  script:
    - PLONE=plone50
      PYTHON=python27
      make nix-show
    - BUILDOUT_ARGS="-N install pocompile test"
      LC_ALL=C
      PLONE=plone50
      PYTHON=python27
      ROBOT_BROWSER=headlessfirefox
      make nix-test
  artifacts:
    paths:
      - parts/test
